package com.pagatodoholdings.posandroid.utils.enums;

public enum IdEvento {
    HOME_MENU_SELECCIONADO,
    HOME_NIVEL_MENU,
    HOME_TITULOS_CATEGORIAS_MENU,
    HOME_ICONOS_CATEGORIAS_MENU,
    HOME_CATEGORIA_SELECCIONADA,
    HOME_CARGAR_MENU_CATEGORIAS,
    HOME_CARGAR_PRODUCTOS_DE_CATEGORIA,
    HOME_MOSTRAR_FRAGMENT_FORMULARIO_PRODUCTO,
    HOME_MOSTRAR_FRAGMENT_SUBMENU_PRODUCTO,
    HOME_SALIR_APP,
    CONFIGURACION_ACTUALIZAR_PRODUCTOS,
    CONFIGURACION_CIERRE_TURNO,
    CONFIGURACION_REPORTE_VENTAS,
    CONFIGURACION_AYUDA,
    CONFIGURACION_CONTACTANOS,
    CONFIGURACION_SALIR_APP,
    CONFIGURACION_BIENVENIDO,
    CONFIGURACION_EJECUTAR_RESTAURACION_FABRICA,
    CONFIGURACION_FRAGMENT_RESTURACION_FABRICA,
    SOLICITAR_SALDO
}
